#ifndef USBUTIL_ERRNO_H
#define USBUTIL_ERRNO_H

#define USBUTIL_EOPEN 0x10
#define USBUTIL_MALLOC_FAIL 0x11
#define USBUTIL_GETKERNEL 0x12
#define USBUTIL_KERNELVERSION 0x13
#define USBUTIL_NOT_FOUND 0x14

#endif